<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <RootNamespace>ILNumerics.Community.Interactive</RootNamespace>
    <AssemblyName>ILNumerics.Community.Interactive</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILNumerics.Community.TikzExport" Version="7.0.0.247" />
    <PackageReference Include="ILNumerics.Community.WebExport" Version="7.0.0.247" />
    <PackageReference Include="ILNumerics.Computing" Version="7.2.41" />
    <PackageReference Include="ILNumerics.Drawing" Version="7.2.41" />
    <PackageReference Include="Microsoft.DotNet.Interactive.CSharp" Version="1.0.0-beta.25323.1" />
    <PackageReference Include="Microsoft.DotNet.Interactive.Formatting" Version="1.0.0-beta.25323.1" />
    <PackageReference Include="MinVer" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <None Include="$(ProjectDir)..\README.md" Pack="true" PackagePath="\" />
    <None Include="extension.dib" Pack="true" PackagePath="interactive-extensions/dotnet" />
  </ItemGroup>

</Project>
